version: '3.7'

services:
  kong-database:
    image: postgres:13
    container_name: kong-database
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    volumes:
      - kong-database-data:/var/lib/postgresql/data
    networks:
      - kong-network

  kong-migration:
    image: kong:latest  # Replace with the Kong Enterprise image if you have access
    container_name: kong-migration
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
    entrypoint: ["kong", "migrations", "bootstrap"]
    networks:
      - kong-network

  kong:
    image: kong:latest  # Replace with the Kong Enterprise image if you have access
    container_name: kong
    restart: always
    depends_on:
      - kong-migration
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl
      KONG_PORTAL_GUI_HOST: 0.0.0.0:8002
      KONG_PORTAL: on
      KONG_LICENSE_DATA: <your_license_key_here>  # Required for Kong Enterprise
    ports:
      - "8000:8000"  # Kong Proxy
      - "8443:8443"  # Kong Proxy SSL
      - "8001:8001"  # Kong Admin
      - "8444:8444"  # Kong Admin SSL
      - "8002:8002"  # Kong Manager
    networks:
      - kong-network
    volumes:
      - kong-data:/usr/local/kong

volumes:
  kong-database-data:
  kong-data:

networks:
  kong-network:
    driver: bridge