services:
  test-kong-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - kong-poc_kong-network

networks:
  kong-poc_kong-network:
    external: true
    driver: bridge
    name: kong-poc_kong-network